version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: cargo
    directory: '/actix-web-reqwest-example/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      actix-web-reqwest:
        patterns:
          - '*'

  - package-ecosystem: cargo
    directory: '/rust-cassandra-example/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      cassandra:
        patterns:
          - '*'

  - package-ecosystem: cargo
    directory: '/rust-dynamodb-example/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      dynamodb:
        patterns:
          - '*'

  - package-ecosystem: cargo
    directory: '/rust-fizzbuzz/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      fizzbuzz:
        patterns:
          - '*'

  - package-ecosystem: cargo
    directory: '/rust-iron-example/app/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      iron:
        patterns:
          - '*'

  - package-ecosystem: cargo
    directory: '/rust-mongodb/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      mongodb:
        patterns:
          - '*'
