version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    rebase-strategy: auto
    cooldown:
      default-days: 3
    assignees:
      - poad
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: cargo
    directories: 
      - '/actix-web-reqwest-example/'
      - '/rust-cassandra-example/'
      - '/rust-dynamodb-example/'
      - '/rust-fizzbuzz/'
      - '/rust-mongodb/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    cooldown:
      default-days: 7
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      cargo:
        patterns:
          - '*'
