version: '3.7'
services:
  postgres:
    build:
      context: .
      dockerfile: dockerfile/database/Dockerfile
    container_name: postgres-rust-iron-example
    environment:
      POSTGRES_PASSWORD: ""
    ports:
      - 5432:5432
    networks:
      - rust-iron-example-network
  frontend:
    build:
      context: .
      dockerfile: dockerfile/app/Dockerfile
    container_name: rust-iron-example
    environment:
      RUST_LOG: info
    ports:
      - 3000:3000
    links:
      - postgres
    networks:
      - rust-iron-example-network
networks:
  rust-iron-example-network:
  default:
    external:
      name: rust-iron-example-network
