[package]
name = "rust_mongodb"
version = "0.1.0"
authors = ["Kenji Saito <ken-yo@mbr.nifty.com>"]
edition = "2018"

[dependencies]
iron = "*"
router = "*"
dotenv = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
env_logger = "*"
persistent = "*"
mongodb = "*"
bson = "*"
log = "*"
percent-encoding = "*"

[dependencies.urlencoded]
version = "*"

[dependencies.bodyparser]
git = "https://github.com/iron/body-parser.git"

[dependencies.logger]
git = "https://github.com/iron/logger.git"