name: Rust

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        path: 
          - actix-web-reqwest-example
          - rust-cassandra-example
          - rust-dynamodb-example
          - rust-fizzbuzz
          - rust-iron-example/app
          - rust-mongodb

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd ${{ matrix.path }}
        cargo build --verbose
    - name: Run tests
      run: |
        cd ${{ matrix.path }}
        cargo test --verbose
